proxy:
 image: proxy:1.0
 links:
  - identidock
 ports:
  - "80:80"
 environment:
  NGINX_HOST: "www.identidock.com"
  NGINX_PROXY: "http://identidock:9090"

identidock:
 image: registry:5000/identidock:newest
 environment:
  ENV: PROD
 links:
  - dnmonster
  - redis

dnmonster:
 image: amouat/dnmonster:1.0

redis:
 image: redis:3.0

logspout:
 image: amouat/logspout-logstash
 volumes:
  - /var/run/docker.sock:/tmp/docker.sock
 ports:
  - "8000:80"
 links:
  - logstash
 command: logstash://logstash:5000

logstash:
 image: logstash
 volumes:
  - ./logstash.conf:/etc/logstash.conf
 environment:
  LOGSPOUT: ignore
 links:
  - elasticsearch
 command: -f /etc/logstash.conf

elasticsearch:
 image: elasticsearch:1.7
 evironment:
  LOGSPOUT: ignore
kibana:
 image
  ELASTICSEARCH_URL: http://elasticsearch:9200
 links:
  
