proxy:
 image: proxy:1.0
 links:
  - identidock
 ports:
  - "80:80"
 environment:
  NGINX_HOST: "www.identidock.com"
  NGINX_PROXY: "http://identidock:9090"
identidock:
 image: registry:5000/identidock:newest
 environment:
  ENV: PROD
 links:
  - dnmonster
  - redis
dnmonster:
 image: amouat/dnmonster:1.0
redis:
 image: redis:3.0
